name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        if [ "$GOOS" = "windows" ]; then
          go build -ldflags="-s -w" -o gvm-$GOOS-$GOARCH.exe main.go
        else
          go build -ldflags="-s -w" -o gvm-$GOOS-$GOARCH main.go
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gvm-${{ matrix.goos }}-${{ matrix.goarch }}
        path: gvm-*

  release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Prepare release files
      run: |
        mkdir -p release
        find . -name "gvm-*" -type f -exec cp {} release/ \;

        # Create main gvm.exe for Windows (default)
        if [ -f "release/gvm-windows-amd64.exe" ]; then
          cp release/gvm-windows-amd64.exe release/gvm.exe
        fi

        # Create checksums
        cd release
        sha256sum * > checksums.txt
        ls -la

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Installation

          ### One-line Installation (recommended)

          **PowerShell (Windows):**
          ```powershell
          iwr -useb https://raw.githubusercontent.com/David-Coach-Dev/gvm/main/install-nvm-style.ps1 | iex
          ```

          **Bash (Linux/macOS):**
          ```bash
          curl -o- https://raw.githubusercontent.com/David-Coach-Dev/gvm/main/install.sh | bash
          ```

          ### Manual Installation

          1. Download the appropriate binary for your system
          2. Add it to your PATH
          3. Start using GVM!

          ## Changes

          See the changelog below for detailed changes in this release.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
